### ISSUE TITLE
这是啥？

### ISSUE THREAD

**Issue by wenxin-bupt** [daquexian/simple_program_synthesis#1]

**Comment by daquexian** [comment]
program synthesis，大概是给出一个要求，然后程序自动生成符合要求的代码 -w- 

具体是给出几个输入输出的例子，由程序生成符合这些例子的处理字符串的代码（DSL），然后就可以用这个代码去处理新的字符串了

具体可以看[这篇文章](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/popl11-synthesis.pdf)，参照这个做的

**Comment by daquexian** [comment]
用于某门课的期末作业，时间很赶所以没有实现完全> <

**Comment by wenxin-bupt** [comment]
噢噢噢噢！

> 具体是给出几个输入输出的例子，由程序生成符合这些例子的处理字符串的代码（DSL），然后就可以用这个代码去处理新的字符串了

很有意思啊！

你是谷粉干嘛老跟微软的搞在一起。（知识没有疆界么 （老气横秋

**Comment by daquexian** [comment]
> 很有意思啊！

说是“代码”，其实就是一个自动机

> 你是谷粉干嘛老跟微软的搞在一起

而且过几天我就要潜入敌方大本营了

**Comment by wenxin-bupt** [comment]
666

**Comment by wenxin-bupt** [comment]
File "uu.py", line 351, in intersect
    p1 = intersect_pos(op1.p1, op2.p1)
  File "uu.py", line 312, in intersect_pos
    rl1 = intersect_regex(op1.reg_list1, op2.reg_list1)
  File "uu.py", line 327, in intersect_regex
    res = [tuple(set(rl1[i]) & set(rl2[i])) for i in range(len(rl1))]
  File "uu.py", line 327, in <listcomp>
    res = [tuple(set(rl1[i]) & set(rl2[i])) for i in range(len(rl1))]
TypeError: unhashable type: 'StartToken'

？

**Comment by wenxin-bupt** [comment]
为啥输入你的例子的第二个就..了

```
Central Intelligence Agency,CIA
World Wide Web,WWW
Traceback (most recent call last):
  File "uu.py", line 565, in <module
```

win10

**Comment by daquexian** [comment]
好像应该用 py2。。囧

**Comment by wenxin-bupt** [comment]
有空再测啦， win上面木有py2

**Comment by daquexian** [comment]
我更新了，现在可以了，好囧

**Comment by wenxin-bupt** [comment]
在JD?
